//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatJsMvcSample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatConversation
    {
        public ChatConversation()
        {
            this.ChatUserConversations = new HashSet<ChatUserConversation>();
        }
    
        public int Id { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public int RoomId { get; set; }
    
        public virtual ChatRoom ChatRoom { get; set; }
        public virtual ICollection<ChatUserConversation> ChatUserConversations { get; set; }
    }
}
