//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatJsMvcSample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ChatMessages = new HashSet<ChatMessage>();
            this.ChatUserConversations = new HashSet<ChatUserConversation>();
            this.ChatRoomUsers = new HashSet<ChatRoomUser>();
        }
    
        public int Id { get; set; }
        public string PasswordHash { get; set; }
        public string Email { get; set; }
        public string PasswordSalt { get; set; }
        public string DisplayName { get; set; }
    
        public virtual ICollection<ChatMessage> ChatMessages { get; set; }
        public virtual ICollection<ChatUserConversation> ChatUserConversations { get; set; }
        public virtual ICollection<ChatRoomUser> ChatRoomUsers { get; set; }
    }
}
